### ISSUE TITLE
'PyRep' object has no attribute '_step_lock'

### ISSUE THREAD

**Issue by el-cangrejo** [unifyai/demo-utils#1]
When running the scene_utils.py I get the error: 

> 'PyRep' object has no attribute '_step_lock'

from this line: https://github.com/ivy-dl/demo-utils/blob/1599c66f33fb19621ba5e3c3f6e45b15b09c330c/ivy_demo_utils/ivy_scene/scene_utils.py#L281

It seems that in the latest commit (https://github.com/stepjam/PyRep/commit/603d283f02faf4c9874ddbd931bf7bafb3ea50ad) in master branch of PyRep they removed the _step_lock from the PyRep class and made it a global variable in the backend/utils.py

**Comment by djl11** [comment]
Thanks for pointing this out @el-cangrejo.
This is now fixed in the latest release.
